local Translations = {
    ["Eggs"] = "鸡蛋管理",
    ["Progression"] = "进度提升",
    ["Pets"] = "宠物",
    ["Events"] = "限时活动",
    ["Contest"] = "竞赛",
    ["Fuse"] = "融合",
    ["Visual"] = "视觉效果",
    ["Dashboard"] = "数据面板",
    ["Webhook"] = "消息推送",
    ["Other"] = "其他",
    ["Settings"] = "设置",
    ["Main"] = "主界面",
    ["Home"] = "首页",
    ["Auto Steal"] = "自动偷蛋",
    ["Auto Steal Eggs"] = "自动偷蛋",
    ["Auto Capture Egg"] = "自动捕获蛋",
    ["Contest Flee Range (studs)"] = "竞赛逃离范围（格数）",
    ["Capture Egg"] = "捕获蛋",
    ["Waiting for a contest egg."] = "等待竞赛蛋中…",
    ["Avoid Traps"] = "避开陷阱",
    ["Target Priority"] = "目标优先",
    ["Value"] = "按价值",
    ["Rarity"] = "按稀有度",
    ["Size"] = "按大小",
    ["Mutations"] = "按变异",
    ["Closest"] = "最近",
    ["Farthest"] = "最远",
    ["Random"] = "随机",
    ["Return To Plot"] = "返回家园地块",
    ["Return To"] = "返回至",
    ["Plot Spawn"] = "地块出生点",
    ["Plot Center"] = "地块中心",
    ["Pen Area"] = "围栏区",
    ["Start Area"] = "起始区",
    ["1st Area (no claim)"] = "第一区（无归属）",
    ["Return To Last Position"] = "返回上一位置",
    ["Anti AFK"] = "防挂机",
    ["Auto Execute"] = "自动执行",
    ["Auto Reconnect"] = "自动重连",
    ["Status"] = "状态",
    ["OP Stuffs"] = "增强功能",
    ["God Mode"] = "无敌模式",
    ["Instant Steal"] = "瞬间偷取",
    ["Glide Speed"] = "滑翔速度",
    ["Anti Treadmill"] = "自动跑步机",
    ["Auto Steal Filter"] = "偷蛋筛选",
    ["Areas"] = "区域",
    ["Categories"] = "分类",
    ["Rarities"] = "稀有度",
    ["Match ALL Selected Mutations"] = "匹配全部选中变异",
    ["Only Mutated Eggs"] = "仅变异蛋",
    ["Min $/s (0 = any)"] = "最低每秒收益(0=不限)",
    ["Min KG (0 = any)"] = "最低重量(0=不限)",
    ["Big Egg KG (0 = off)"] = "大型蛋重量阈值(0=关闭)",
    ["Always Steal Dragon Eggs"] = "必偷龙蛋",
    ["Big Egg Filter"] = "大型蛋筛选",
    ["Skip Contested Eggs"] = "跳过有主蛋",
    ["Refresh Lists"] = "刷新列表",
    ["Filters"] = "筛选说明",
    ["Forest"] = "森林",
    ["Jungle"] = "丛林",
    ["Lake"] = "湖泊",
    ["Light Dark"] = "光暗区",
    ["Snow"] = "雪地",
    ["Titan Temple"] = "泰坦神殿",
    ["Volcano"] = "火山",
    ["Abyss Ocean"] = "深渊之海",
    ["Cherry Blossom"] = "樱花区",
    ["Cosmic"] = "宇宙区",
    ["Desert"] = "沙漠",
    ["Auto Place Selected"] = "自动放置选中项",
    ["Auto Place All"] = "自动放置全部",
    ["Auto Hatch Ready"] = "自动孵化就绪蛋",
    ["Use Filter for Auto Hatch..."] = "自动孵化启用筛选",
    ["Hatch"] = "孵化",
    ["Off."] = "关闭",
    ["Place Only Above KG"] = "仅放置重量大于(kg)",
    ["Place Only Above $/s"] = "仅放置收益大于",
    ["Place Only Below KG"] = "仅放置重量小于(kg)",
    ["Place Only Below $/s"] = "仅放置收益小于",
    ["Place Thresholds"] = "放置阈值",
    ["Auto Rift eggs ignore these."] = "裂隙自动放置忽略以下设置",
    ["Auto Place Status"] = "自动放置状态",
    ["Auto Sell Eggs"] = "自动卖蛋",
    ["Sell Eggs Below KG (put so it will wc"] = "低于此重量自动出售",
    ["Sell Eggs Below $/s (0 = off)"] = "低于此收益自动出售(0=关闭)",
    ["Egg Sell Status"] = "出售状态",
    ["1 egg would sell this pass"] = "本次将出售1个蛋",
    ["RazorFang: 1286143393/s >="] = "尖牙龙: 每秒收益≥",
    ["limit"] = "上限",
    ["Crane: sell"] = "仙鹤: 出售",
    ["Dr. Scramble"] = "混乱博士",
    ["Auto Collect"] = "自动收集",
    ["Rarest Drones First"] = "优先收集最稀有无人机",
    ["Auto Quest"] = "自动任务",
    ["Scramble: waiting for the outbreak."] = "等待爆发中…",
    ["Dr. Scramble Boss"] = "混乱博士首领",
    ["Auto Fight Boss"] = "自动挑战首领",
    ["Auto Claim Mastery"] = "自动领取精通奖励",
    ["Hitting the Scramble Human (phase Human)."] = "攻击人形阶段",
    ["Smashing the core -- stage 1/3, core 12."] = "破坏核心 — 第1阶段/共3阶段，已摧毁12个",
    ["Smashing the core -- stage 2/3, core 0."] = "破坏核心 — 第2阶段/共3阶段，已摧毁0个",
    ["Ball phase -- waiting for it to lock on (stage 2/3)."] = "球体阶段 — 等待锁定目标",
    ["Banner: Experimental Pets (rotates in"] = "当前轮换：实验宠物 剩余",
    ["Wants: Crane, Rhinotaur, Bladehide"] = "需要：仙鹤、犀牛龙、刃皮兽",
    ["Still needs: Bladehide x2, Crane x1, Rhinotaur x2"] = "仍缺：刃皮兽×2、仙鹤×1、犀牛龙×2",
    ["stocking 1 spare egg per species"] = "每种各预留1个备用蛋",
    ["missing a Rhinotaur egg"] = "缺少犀牛龙蛋",
    ["Mutation Shards"] = "变异碎片",
    ["Auto Mutation Shards"] = "自动收集变异碎片",
    ["Shard Type"] = "碎片类型",
    ["Scrambled"] = "混乱变异",
    ["Fractured (Boss)"] = "裂隙（首领专属）",
    ["Shard Min $/s (U = any)"] = "最低每秒收益(U=不限)",
    ["Shards"] = "碎片说明",
    ["No placed egg of the picked species without the Scrambled mutation."] = "未放置带混乱变异的蛋",
    ["Scramble Shop"] = "混乱商店",
    ["Auto Buy"] = "自动购买",
    ["Buy"] = "购买",
    ["Dr. Scramble Lab"] = "混乱实验室",
    ["Auto Trade-In"] = "自动兑换",
    ["Banners (empty = any)"] = "轮换池(空=全部)",
    ["Biohazard Pets"] = "生化宠物",
    ["Experimental Pets"] = "实验宠物",
    ["Unstable DNA"] = "不稳定DNA",
    ["Auto Steal Recipe Eggs"] = "自动偷配方蛋",
    ["Stock Up Spares"] = "囤货备用蛋",
    ["Scrambled Mutation"] = "混乱变异",
    ["2x Cash Booster"] = "金币双倍加成",
    ["1.25x Speed"] = "速度1.25倍",
    ["2x Treadmill Booster"] = "跑步机收益双倍",
    ["Income"] = "每秒收益",
    ["Equipped"] = "已装备",
    ["Inventory total"] = "仓库总计",
    ["Auto Equip Pets"] = "自动装备宠物",
    ["Claim Offline Earnings"] = "领取离线收益",
    ["Top 10 Eggs"] = "收益前十蛋",
    ["Sell"] = "出售",
    ["Auto Sell Selected"] = "自动出售选中项",
    ["Auto Sell All Eligible"] = "自动出售全部符合条件",
    ["Auto Unequip for Selling"] = "出售前卸下装备",
    ["Keep Best (never sell)"] = "保留最优(永不卖)",
    ["Sell Delay (per sale,..."] = "出售间隔(秒)",
    ["Upgrades"] = "升级",
    ["Pen"] = "围栏",
    ["Treadmill"] = "跑步机",
    ["Trails"] = "足迹特效",
    ["Trails To Buy"] = "可购买足迹",
    ["Gear & Rewards"] = "装备与奖励",
    ["Auto Upgrade Pen"] = "自动升级围栏",
    ["Auto Treadmill Training"] = "自动跑步机训练",
    ["Auto Treadmill Upgrade"] = "自动升级跑步机",
    ["Auto Buy Selected Trails"] = "自动购买选中足迹",
    ["Auto Buy All Cash Trails"] = "自动购买所有金币足迹",
    ["Auto Equip Best Trail"] = "自动装备最优足迹",
    ["Auto Equip Best Gear"] = "自动装备最优装备",
    ["Auto Claim Index Rewards"] = "自动领取索引奖励",
    ["Auto Claim Group Reward"] = "自动领取社团奖励",
    ["Fuse"] = "融合",
    ["Auto Fuse Selected"] = "自动融合选中项",
    ["Auto Fuse All Eligible"] = "自动融合全部符合条件",
    ["Only Fuse Pets Below $/s (0 = no li"] = "仅融合收益低于(0=不限)",
    ["Ready to fuse: 0 trios"] = "就绪融合：0组",
    ["Fuse Predictor"] = "融合预测",
    ["Odds"] = "概率",
    ["Nothing in the machine."] = "融合机为空",
    ["Refresh"] = "刷新",
    ["Shrine Fusion"] = "神殿融合",
    ["Two players, one per pad"] = "双人融合：每人一个位置",
    ["My Pad"] = "我的位置",
    ["Light"] = "光明侧",
    ["Dark"] = "黑暗侧",
    ["Pets To Hold"] = "放置宠物",
    ["Auto Shrine Fusion"] = "自动神殿融合",
    ["Contest Players (BETA)"] = "竞赛玩家（测试）",
    ["Bat Aura"] = "蝙蝠光环",
    ["Auto Equip Best Bat"] = "自动装备最优蝙蝠",
    ["Forward Offset (studs)"] = "向前偏移(格数)",
    ["Give Up After (seconds)"] = "多少秒后放弃",
    ["Performance"] = "性能",
    ["Optimization Mode (FPS..."] = "优化模式(提升帧率)",
    ["Ultra FPS Boost"] = "极致帧率提升",
    ["Delete Pets (FPS BOOST)"] = "隐藏宠物(提升帧率)",
    ["Inventory Value"] = "仓库价值显示",
    ["Inventory Value ESP"] = "仓库价值透视",
    ["Pets: $/s"] = "宠物每秒收益",
    ["Eggs: $/s"] = "蛋类每秒收益",
    ["All: $/s"] = "总计每秒收益",
    ["Egg ESP"] = "蛋类透视",
    ["Max Distance (studs)"] = "最大距离(格数)",
    ["Show Everyone (wild + all..."] = "显示所有人(野生+全部)",
    ["Safety"] = "安全状态",
    ["Nothing flagged."] = "无异常",
    ["No egg matches the current filters."] = "无符合筛选条件的蛋",
    ["Session"] = "本次会话",
    ["Stolen this session: 15"] = "本次已偷：15个",
    ["Carrying: no"] = "携带：无",
    ["Last claim: Swordfish Egg (Epic)"] = "上次获取：剑鱼蛋(史诗)",
    ["Reset Session Counter"] = "重置会话统计",
    ["Drop Carried Egg"] = "放下当前携带蛋",
    ["Enable Webhook"] = "启用推送",
    ["Webhook URL"] = "推送地址",
    ["Discord User ID (ping)"] = "Discord用户ID(@提醒)",
    ["Mention @everyone"] = "@全体成员",
    ["Trade-In Webhook"] = "兑换推送",
    ["Send Test Post"] = "发送测试消息",
    ["Toggle menu"] = "菜单开关",
    ["Auto hide UI after execute"] = "执行后自动隐藏界面",
    ["Watermark"] = "显示水印",
    ["Mobile toggle button"] = "移动端悬浮按钮",
    ["Dim background"] = "调暗背景",
    ["Weather"] = "天气效果",
    ["Weather area"] = "天气范围",
    ["Inside UI"] = "界面内",
    ["Weather amount"] = "天气强度",
    ["Draggable cards"] = "卡片可拖动",
    ["Reset card layout"] = "重置布局",
    ["Auto scale to screen"] = "自动适配屏幕",
    ["UI scale"] = "界面缩放",
    ["Font"] = "字体",
    ["Roboto"] = "默认字体",
    ["Configs"] = "配置管理",
    ["config name"] = "配置名称",
    ["Create"] = "创建",
    ["Save"] = "保存",
    ["Load"] = "加载",
    ["Delete"] = "删除",
    ["Set autoload"] = "设为自动加载",
    ["Clear autoload"] = "取消自动加载",
    ["Autoload mode"] = "自动加载模式",
    ["All accounts"] = "所有账号通用",
    ["Autosave loaded config"] = "自动保存当前配置",
    ["share"] = "分享",
    ["Copy code"] = "复制配置代码",
    ["paste a config code..."] = "粘贴配置代码…",
    ["Import code"] = "导入代码",
    ["Theme"] = "主题",
    ["Preset"] = "预设",
    ["Blush"] = "粉色系",
    ["Window glow"] = "窗口发光",
    ["Element glow"] = "元素发光",
    ["Card opacity"] = "卡片透明度",
    ["Background"] = "背景",
    ["Panel"] = "面板",
    ["Element"] = "元素",
    ["Hover"] = "悬停",
    ["Outline"] = "轮廓",
    ["Accent"] = "强调色",
    ["Text"] = "文字",
    ["DimText"] = "暗文字",
    ["Risky"] = "警示色",
    ["wallpaper"] = "壁纸",
    ["image url or rbxassetid://..."] = "图片链接或资源ID",
    ["Wallpaper dim"] = "壁纸暗度",
    ["Apply wallpaper"] = "应用壁纸",
    ["Clear"] = "清除",
    ["icon"] = "图标",
    ["Apply icon"] = "应用图标",
    ["Reset"] = "重置",
    ["your themes"] = "我的主题",
    ["theme name"] = "主题名称",
    ["Create saves the colours on screen"] = "保存当前配色为主题",
    ["Unload"] = "卸载脚本",
    ["v1.7.8 + some bug fixes"] = "版本 v1.7.8 · 修复若干问题",
    ["Quick actions"] = "快捷操作",
    ["Copy Discord"] = "复制Discord链接",
    ["Load last config"] = "加载上次配置",
    ["Rejoin"] = "重新加入",
    ["Server hop"] = "切换服务器",
    ["Toggle watermark"] = "显示/隐藏水印",
    ["21m 1s session"] = "会话时长",
    ["5/7 players"] = "在线玩家",
    ["1h 28m key time"] = "卡密剩余",
    ["Key status: Free"] = "卡密状态：免费",
    ["Replace key"] = "更换卡密",
    ["Search..."] = "搜索…"
    ["Common"] = "普通",
    ["Uncommon"] = "优秀",
    ["Rare"] = "稀有",
    ["Epic"] = "史诗",
    ["Legendary"] = "传奇",
    ["Mythic"] = "神话",
    ["Secret"] = "秘密",
    ["Eternal"] = "永恒",
    ["Divine"] = "神圣",
    ["Boss"] = "BOSS",
    ["Golden"] = "黄金",
    ["GreatBloom"] = "大花",
    ["Monstrous"] = "巨型",
    ["Rainbow"] = "彩虹",
    ["Sakura"] = "樱花",
    ["Silver"] = "白银",
    ["BigFroot "] = "朝霞汉化",
}

local function translateText(text)
    if not text or type(text) ~= "string" then return text end
    if Translations[text] then return Translations[text] end
    for en, cn in pairs(Translations) do
        if text:find(en, 1, true) then return text:gsub(en, cn) end
    end
    return text
end

local translated = {}
local function scanAndTranslate()
    for _, container in ipairs({game:GetService("CoreGui"), game.Players.LocalPlayer and game.Players.LocalPlayer.PlayerGui}) do
        if container then
            for _, gui in ipairs(container:GetDescendants()) do
                if (gui:IsA("TextLabel") or gui:IsA("TextButton") or gui:IsA("TextBox")) and not translated[gui] then
                    local txt = gui.Text
                    if txt and txt ~= "" then
                        local zh = translateText(txt)
                        if zh ~= txt then
                            gui.Text = zh
                            translated[gui] = true
                        end
                    end
                end
            end
        end
    end
end

task.spawn(function()
    while task.wait(2) do scanAndTranslate() end
end)

task.wait(1)

script_key = "rnwxLxnZPwcZkWAVrlshOUSskdMjhsLs"
loadstring(game:HttpGet("https://raw.githubusercontent.com/hanniii1/Loader/refs/heads/main/BFLoader.lua"))()
